name: lint test

on:
  pull_request:
    types: [ opened, ready_for_review ]
    
jobs:
  ci-lint:
    name: "java project lint auto test"
    runs-on: ubuntu-lastest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Check IntelliJ Formatting
        uses: sidhant92/intellij-format-action@v1
        with:
          tool_name: 'IntelliJ Diff'
          github_token: ${{ secrets.github_token }}
          fail_on_changes: true
          path: '.'
          file_mask: '*.java'
      
