name: lint test

on:
  pull_request:
    types: [ opened, ready_for_review ]
    branch:
      - '*'

jobs:
  formatting:
    name: Lint 검사기
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.ref }}

      - uses: notdevcody/intellij-format-action@v1.1
        with:
          path: './backend/src'
          commit-on-changes: 'true'
          commit-message: '코드 컨벤션 확인해라'
          style-settings-file: '${{ github.workspace }}/backend/code-style-format.xml'
